### ISSUE TITLE
Upload the Screenshot of the image to the repo to be displayed on README.md File

### ISSUE THREAD

**Issue by usrbinomarbash** [omarbelkady/Linux#1]
![Uploading Screenshot 2020-08-03 at 3.47.17 AM.png…]()

![Screenshot 2020-08-03 at 3 10 03 AM](https://user-images.githubusercontent.com/31806568/89141652-1b8a6f00-d53d-11ea-9312-3431d471ea1c.png)

**Comment by usrbinomarbash** [comment]
![Screenshot 2020-08-03 at 3 47 03 AM](https://user-images.githubusercontent.com/31806568/89141725-5391b200-d53d-11ea-8a35-0d81bc524461.png)

**Comment by omarbelkady** [comment]
![Screenshot 2020-08-03 at 3 10 03 AM](https://user-images.githubusercontent.com/31806568/89141783-7d4ad900-d53d-11ea-8441-614300cd7bdb.png)
